# Generated by Django 5.0.7 on 2024-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile_Image1', models.ImageField(blank=True, null=True, upload_to='mobile pictures')),
                ('Mobile_Image2', models.ImageField(blank=True, null=True, upload_to='mobile pictures')),
                ('Mobile_Image3', models.ImageField(blank=True, null=True, upload_to='mobile pictures')),
            ],
        ),
    ]
